### ISSUE TITLE
Missing licence/license information

### ISSUE THREAD

**Issue by peterjc** [ordinaryzelig/entrez#1]
Please add licence information to the main README or a dedicated LICENSE file. e.g. The MIT License http://opensource.org/licenses/MIT is a popular choice for Ruby Gems.

For this to be listed on https://rubygems.org/gems/entrez you will also need to add the licence to your `entrez.gemspec` file as described on  http://guides.rubygems.org/specification-reference/#license=

e.g.

```
    s.license = "MIT"
```

**Comment by ordinaryzelig** [comment]
Added in 02d3103d0b29e04607b56fc1a775506f7f7fa75e

**Comment by ordinaryzelig** [comment]
Just FYI, this gem is no longer being maintained and hasn't been for many years.

**Comment by peterjc** [comment]
Thanks. At least now you've clearly released this under the MIT licence someone might be interested in taking this over...

(I just followed a link from http://biogems.info/ to discover it)
